### ISSUE TITLE
/turbo/log.py basestring error in python3

### ISSUE THREAD

**Issue by iakisey** [wecatch/app-turbo#57]

**Comment by zhyq0826** [comment]
@iakisey turbo 现在还不支持 python 3，需要改动不少代码来兼容 python 2 并支持 python 3，未来几个版本会逐步向 python 3 过渡

**Comment by leeyisoft** [comment]
期望情况支持Python3.6

**Comment by biggers** [comment]
**Would like Python-3.5+ support, with Tornado 5.0+**.   This is one of the "more complete" add-ons for Tornado, which has few good ones (that are not obsolete).  Thank you.

**Comment by zhyq0826** [comment]
@biggers Python 3 will be supported soon later.
